### ISSUE TITLE
Discussion: Handle subscription (React)

### ISSUE THREAD

**Issue by dmicic** [ryardley/ts-bus#19]
Some random thoughts which went through my mind in regards to the subscription management. 

- Is there a way to unsubscribe from an event? I expected the EventBus to have a unsubscribe function.
- What are the best practises to set up a subscription? Let's say, component B subscribes to events published by component A.
```ts
bus.subscribe("componentA.event", handler)
```
Now let's say component B gets re-rendered to do some changes in the data. As a result, the code above will execute again and it will subscribe 'probably' for the 2nd time to events from component A. Will the bus still keep a reference to the old handler?
If so, would it be better to use the useEffect() hook with the 'bus' dependency in order to avoid obsolete subscriptions? 
```ts
useEffect(() => {
  bus.subscribe("componentA.event", handler)
}, [bus]);

```
And should the useEffect() also cleanup the subscription when the component B unmounts? (goes back to the first bullet point)
This here would be my preferred solution. Would be good to have a hook for that to avoid boilerplate code.
```ts
useEffect(() => {
  bus.subscribe("componentA.event", handler)
  
  return function cleanup() {
      bus.unsubscribe("componentA.event", handler)
    };

}, [bus]);

```

**Comment by dmicic** [comment]
Ah, I saw now that the subscribe method returns a function which can be used to unsubscribe. 

https://github.com/ryardley/ts-bus/blob/4fd905f0e17ea52803586620c462f342592d9666/src/EventBus.ts#L68

**Comment by ryardley** [comment]
That is correct mind I close this?
