### ISSUE TITLE
Swap useBusReducer input args to be more inline with useReducer

### ISSUE THREAD

**Issue by ryardley** [ryardley/ts-bus#22]
useBusReducer should have input args swapped as a breaking change. 

This means it can act as a drop in replacement for useReducer.

This could be coordinated with an API change to accomodate https://github.com/ryardley/ts-bus/issues/15

Also making it so that we can remove the custom subscriber function in favour of a predicate or a wildcard string filter

**Comment by dmicic** [comment]
I guess this one can be closed now.
