### ISSUE TITLE
Subscribe to an array of event names / wildcard definitions

### ISSUE THREAD

**Issue by dmicic** [ryardley/ts-bus#37]
The bus should allow to subscribe to a list of events.

Example:
```ts
  const state = useBusReducer.configure({
    subscriber: (dispatch, bus) =>  bus.subscribe(["task.**", "signout"], dispatch)
  })(reducer, InitialState);
```
This his helpful in scenarios as above, where the reducer needs to know about a certain event like "signOut" that is not been raised under the event name prefix "task" in order to clean up the state etc.

**Comment by ryardley** [comment]
Sounds great. One idea not attached to it though. Would it be good to provide a functional subscriber to remove the boilerplate?

```
  const state = useBusReducer.configure({
    subscriber: eventSubscriber("task.**", "signout")
  })(reducer, InitialState);
```

**Comment by dmicic** [comment]
+1 for the functional subscriber. And I think the name is good.
