### ISSUE TITLE
Possible interceptor / middleware

### ISSUE THREAD

**Issue by evangelion1204** [ryardley/ts-bus#4]
Hi,

I can also do it myself but before investing time I wondered it would make sense to add support to listen to all events (not via wildcards - which actually not documented but saw it in your code) but through `onAny` of `EventEmitter2`. Typing here could be tricky because it could be any event but in case of just wanting to log the event it might be ok.
For later an interceptor with the possibility to drop events or do similar functionality could be helpful too.

Reason is I want to build a bridge between client and server - I will give it a try with wildcards but in any case it might be more straight forward with the above mentioned approach.

**Comment by ryardley** [comment]
I have an example of exactly this. I will try and publish it tonight if not it will have to be next week.

**Comment by evangelion1204** [comment]
Yeah, build something similar - good idea using `meta` 😄

**Comment by ryardley** [comment]
Just updated the source with an example

**Comment by evangelion1204** [comment]
Cool, will have a look tomorrow
